INSERT INTO `subject` (`name`) VALUES
('Mindegy'),
('Kémia'),
('Matematika'),
('Idegen nyelv'),
('Biológia'),
('Földrajz'),
('Történelem'),
('Irodalom'),
('Nyelvtan'),
('Erkölcstan'),
('Hittan'),
('Környezetismeret'),
('Ének-zene'),
('Vizuális kultúra'),
('Technika'),
('Dráma és tánc'),
('Informatika'),
('Társadalmi és állampolgári imeretek'),
('Hon- és népismeret'),
('Természetismeret'),
('Fizika'),
('Kémia'),
('Etika'),
('Mozgóképkultúra és médiaismeret'),
('Művészetek'),
('Filozófia');
